# Generated by Django 3.2.18 on 2023-03-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0235_auto_20230316_2023'),
        ('grantomy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zeus',
            name='id',
        ),
        migrations.AddField(
            model_name='zeus',
            name='customer_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pretixbase.customer'),
            preserve_default=False,
        ),
    ]
