# Generated by Django 3.2.18 on 2023-03-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantomy', '0007_auto_20230328_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeusdocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
