# Generated by Django 3.2.18 on 2023-03-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0235_auto_20230316_2023'),
        ('grantomy', '0009_alter_zeusdocument_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeusdocument',
            name='document',
            field=models.BinaryField(editable=True),
        ),
        migrations.CreateModel(
            name='ZeusConfiguration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('configuration', models.JSONField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.organizer')),
            ],
        ),
    ]
